AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'notifications-processor infrastructure resources

  '
Parameters:
  Env:
    Type: String
Resources:
  NotificationProcessorLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://bug-sales-artifacts-bucket-dev/notifications-processor-artifacts-dev/18d23df7752a1fae5cd5920e1e669790
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      MemorySize: 128
      Timeout: 30
      Architectures:
      - x86_64
      Environment:
        Variables:
          NODE_OPTIONS: ' --enable-source-maps'
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
        - app.ts
        Minify: true
        Sourcemap: true
        Target: es2020
      SamResourceId: NotificationProcessorLambda
  NotificationsSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Protocol: lambda
        Endpoint:
          Fn::GetAtt:
          - NotificationProcessorLambda
          - Arn
    Metadata:
      SamResourceId: NotificationsSNSTopic
  NotificationProcessorLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: NotificationProcessorLambda
      Principal: sns.amazonaws.com
    Metadata:
      SamResourceId: NotificationProcessorLambdaPermission
  NotificationsTopicSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      DataType: text
      Name:
        Fn::Sub: bug-sales-bot-notifications-processor-sns-topic-${Env}
      Tier: Standard
      Type: String
      Value:
        Fn::GetAtt:
        - NotificationsSNSTopic
        - TopicName
    Metadata:
      SamResourceId: NotificationsTopicSSMParameter
