version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
  build:
    commands:
      - cd web-scraper/
      - docker login -u edgarpdev -p $DOCKER_CREDENTIALS
      - ./build-docker-codebuild.sh
