version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.x
    commands:
      - export BUILDX_VERSION=$(curl --silent "https://api.github.com/repos/docker/buildx/releases/latest" |jq -r .tag_name)
      - curl -JLO "https://github.com/docker/buildx/releases/download/$BUILDX_VERSION/buildx-$BUILDX_VERSION.linux-arm-v6"
      - mkdir -p ~/.docker/cli-plugins
      - mv "buildx-$BUILDX_VERSION.linux-arm-v6" ~/.docker/cli-plugins/docker-buildx
      - chmod +x ~/.docker/cli-plugins/docker-buildx
      - cd web-scraper/
  build:
    commands:
      - docker login -u edgarpdev -p $DOCKER_CREDENTIALS
      - ./build-docker.sh
