AWSTemplateFormatVersion: 2010-09-09

Description: |
  Codebuild template

Parameters:
  Name:
    Type: String
  BuildSpec:
    Type: String
  Env:
    Type: String
  ArtifactsBucket:
    Type: String
    Default: ""

Resources:
  CodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref Name
      Artifacts:
        Type: CODEPIPELINE
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Ref BuildSpec
      Environment:
        Type: ARM_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-aarch64-standard:3.0
        EnvironmentVariables:
          - Name: ARTIFACTS_BUCKET
            Type: PLAINTEXT
            Value: !Ref ArtifactsBucket
          - Name: ENV
            Type: PLAINTEXT
            Value: !Ref Env

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${Name}-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowAssumeRole
            Effect: Allow
            Principal:
              Service: "codebuild.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: CodeBuild
                Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                  - "s3:GetObject"
                  - "s3:CopyObject"
                  - "s3:GetObjectVersion"
                  - "s3:PutObject"
                  - "s3:ListBucket"
                  - "s3:GetBucketAcl"
                  - "s3:GetBucketLocation"
                  - "cloudformation:*"
                  - "iam:*"
                  - "lambda:*"
                  - "ssm:GetParameters"
                  - "scheduler:*"
                  - "dynamodb:*"
                Resource: "*"
          PolicyName: !Sub ${Name}-codebuild-policy

Outputs:
  CodeBuildProjectName:
    Value: !Ref CodeBuild
    Export:
      Name: !Ref Name
