AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
    bug-sales-processor

    Lambda the handle bug sales process

Parameters:
    Env:
        Type: String
        AllowedValues:
            - dev
            - prod

Resources:
    # IAM
    BugSalesProcessorLambdaRole:
        Type: "AWS::IAM::Role"
        Properties:
            RoleName: !Sub bug-sales-processor-role-${Env}
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: Allow
                      Principal:
                          Service: lambda.amazonaws.com
                      Action: "sts:AssumeRole"
            Policies:
                - PolicyName: !Sub bug-sales-processor-policy-${Env}
                  PolicyDocument:
                      Version: "2012-10-17"
                      Statement:
                          - Effect: Allow
                            Action:
                                - "logs:CreateLogGroup"
                                - "logs:CreateLogStream"
                                - "logs:PutLogEvents"
                            Resource: "arn:aws:logs:*:*:*"
                          - Effect: Allow
                            Action:
                                - "dynamodb:PutItem"
                                - "dynamodb:GetItem"
                                - "dynamodb:DeleteItem"
                                - "dynamodb:UpdateItem"
                                - "dynamodb:Query"
                                - "dynamodb:Scan"
                            Resource: !GetAtt BugSalesDB.Arn
                          - Effect: Allow
                            Action:
                                - "sns:Publish"
                            Resource: !Sub "{{resolve:ssm:bug-sales-bot-notifications-processor-sns-topic-arn-${Env}:1}}"

    # LAMBDA
    BugSalesProcessorLambda:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: !Sub bug-sales-processor-${Env}
            CodeUri: src/
            Handler: app.lambdaHandler
            Runtime: nodejs18.x
            Architectures:
                - x86_64
            MemorySize: 128
            Timeout: 30
            Role: !GetAtt BugSalesProcessorLambdaRole.Arn
            Environment:
                Variables:
                    BUG_SALES_DB_NAME: !Ref BugSalesDB
                    NOTIFICATIONS_SNS_TOPIC_ARN: !Sub "{{resolve:ssm:bug-sales-bot-notifications-processor-sns-topic-arn-${Env}:1}}"
            Events:
                HttpPost:
                    Type: Api
                    Properties:
                        Path: "/sales"
                        Method: post
                        RestApiId: !Ref BugSalesProcessorApi
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: "es2020"
                Sourcemap: true
                EntryPoints:
                    - app.ts

    # API GATEWAY
    BugSalesProcessorApi:
        Type: AWS::Serverless::Api
        Properties:
            StageName: !Ref Env
            Auth:
                DefaultAuthorizer: AWS_IAM

    # DYNAMO DB
    BugSalesDB:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: !Sub bug-sales-db-${Env}
            AttributeDefinitions:
                - AttributeName: id
                  AttributeType: S
            KeySchema:
                - AttributeName: id
                  KeyType: HASH
            BillingMode: PAY_PER_REQUEST

    # IAM
    BugSalesProcessorApiRole:
        Type: AWS::IAM::Role
        Properties:
            RoleName: !Sub bug-sales-processor-api-call-rol-${Env}
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: Allow
                      Principal:
                          Service:
                              - lambda.amazonaws.com
                      Action:
                          - "sts:AssumeRole"
            Policies:
                - PolicyName: InvokeApiPolicy
                  PolicyDocument:
                      Version: "2012-10-17"
                      Statement:
                          - Effect: Allow
                            Action: "execute-api:Invoke"
                            Resource: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${BugSalesProcessorApi}/*"

Outputs:
    HelloWorldApi:
        Description: "BugSalesProcessorApi endpoint URL"
        Value: !Sub "https://${BugSalesProcessorApi}.execute-api.${AWS::Region}.amazonaws.com/${Env}/sales/"
